In [1]:
import numpy as np
from keras import layers
from keras.layers import Input, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D
from keras.layers import AveragePooling2D, MaxPooling2D, Dropout, GlobalMaxPooling2D, GlobalAveragePooling2D
from keras.models import Model
from keras.preprocessing import image
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.applications.imagenet_utils import preprocess_input
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import os,math,random,cv2
import keras.backend as K
K.set_image_data_format('channels_last')
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow

%matplotlib inline

Using TensorFlow backend.


In [2]:
def split_train_test():
    categories=[f for f in os.listdir('data') if not f.startswith('.')]
    for c in categories:
        allImages=[f for f in os.listdir('data/'+c) if f.endswith('.jpg') and not f.startswith('.')]
        totalImages=int(len(allImages))
        train_size=int(math.ceil(totalImages*0.7))
        test_size=totalImages-train_size
        random.shuffle(allImages)
        train_images=allImages[:train_size]
        test_images=[item for item in allImages if item not in train_images]
        if not os.path.exists('./data/'+c+'/train'):
            os.makedirs('./data/'+c+'/train')
        if not os.path.exists('./data/'+c+'/test'):
            os.makedirs('./data/'+c+'/test')
        print(len(train_images))
        for i in train_images:
            os.rename('./data/'+c+'/'+i,'./data/'+c+'/train'+'/'+i)
        for i in test_images:
            os.rename("./data/"+c+'/'+i,"./data/"+c+'/test'+'/'+i)
    return categories    

split_train_test()           

0
0
0
0
0
0
0
0


['bed', 'lamp', 'wardrobe', 'stool', 'shelf', 'chair', 'table', 'sofa']

In [3]:
categories=[f for f in os.listdir('data') if not f.startswith('.')]

In [4]:
def returnCategory(n):
    return categories[n]
def returnCatPos(x):
    return categories.index(x)

In [5]:
def load_data():
    X_train=[]
    Y_train=[]
    X_test=[]
    Y_test=[]
    for c in categories:
        print(c)
        train_folder='./data/'+c+'/train/'
        test_folder='./data/'+c+'/test/'
        for i in os.listdir(train_folder):            
            my_image=cv2.imread(train_folder+i)
            resized_image = cv2.resize(my_image, (64, 64)) 
            X_train.append((resized_image))
            Y_train.append(returnCatPos(c))
            
        for i in os.listdir(test_folder):            
            my_image=cv2.imread(test_folder+i)
            resized_image = cv2.resize(my_image, (64, 64)) 
            X_test.append((resized_image))
            Y_test.append(returnCatPos(c)) 
    X_train=np.asarray(X_train)
    Y_train=np.asarray(Y_train)
    X_test=np.asarray(X_test)
    Y_test=np.asarray(Y_test)
    return X_train,Y_train,X_test,Y_test
X_train,Y_train,X_test,Y_test=load_data()

bed
lamp
wardrobe
stool
shelf
chair
table
sofa


In [6]:
print("Number of training samples =",X_train.shape[0])
print("Image dimension =",X_train.shape[1:])

Number of training samples = 2687
Image dimension = (64, 64, 3)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]] 0
